### ISSUE TITLE
Does not work with ember-source 3.27+

### ISSUE THREAD

**Issue by mydea** [ember-polyfills/ember-cached-decorator-polyfill#70]
On 3.27-beta.4, I get the error:

```
Uncaught SyntaxError: Cannot use import statement outside a module
```

![Screenshot from 2021-04-26 14-43-00](https://user-images.githubusercontent.com/2411343/116084135-bf084a80-a69d-11eb-8024-f08e03621413.png)

**Comment by boris-petrov** [comment]
I just hit the same issue when upgrading to Ember 3.27.

@rwjblue, @buschtoens - what should we do?

**Comment by rwjblue** [comment]
This is basically because of 

https://github.com/ember-polyfills/ember-cached-decorator-polyfill/blob/57592832ce0de1cc046af1e3ed7c8ad4506ca799/index.js#L16-L26

Specifically, we are telling ember-cli-babel that it shouldn't compile modules. **But** that isn't going to work quite right (since in Ember 3.27+ the modules are actually directly used).

**Comment by rwjblue** [comment]
Hmm. I'm not able to reproduce (I checked out this repo and ran its tests). Can someone make a quick reproduction so I can debug?

**Comment by boris-petrov** [comment]
@rwjblue - it's as simple as:

```bash
ember new test-test
cd test-test
# modify package.json to use Ember 3.27
ember install ember-cached-decorator-polyfill
ember test -s
```

**Comment by rwjblue** [comment]
I think https://github.com/babel/ember-cli-babel/pull/402 will resolve.

**Comment by rwjblue** [comment]
please test with https://github.com/babel/ember-cli-babel/releases/tag/v7.26.5

**Comment by boris-petrov** [comment]
@rwjblue - the same example I gave above still doesn't work even with 7.26.5. :( My project also doesn't work.

**Comment by knownasilya** [comment]
Same. I'm testing with 3.26.1, and have the same issue.

**Comment by runspired** [comment]
We're also hitting this in EmberData with ember-cli-babel 7.26.5.

**Comment by mydea** [comment]
I made a PR with a refactor to using the approach proposed by @ef4 here: https://github.com/ember-polyfills/ember-cached-decorator-polyfill/pull/75

**Comment by rwjblue** [comment]
I paired with @ef4 to make the changes in ember-cli-babel more correct (well, really they are still kinda bonkers but they more correctly emulate the "old world") in https://github.com/babel/ember-cli-babel/pull/407.

Testing the reproduction steps provided by @boris-petrov results in a passing test run.

**Comment by boris-petrov** [comment]
@rwjblue - thanks! That fixed the error from above... but it still doesn't work. :smile: 

Use the reproduction from above and just add in `app.js`:

```ts
import { cached } from '@glimmer/tracking';

class X {
  @cached
  get foo() {
    return 1;
  }
}
```

Then running `ember serve` leads to:

```
Uncaught TypeError: decorator is not a function
    at applyDecoratedDescriptor.js:22
    at Array.reduce (<anonymous>)
    at _applyDecoratedDescriptor (applyDecoratedDescriptor.js:21)
    at Module.callback (store.js:868)
    at Module.exports (loader.js:106)
    at Module._reify (loader.js:143)
    at Module.reify (loader.js:130)
    at Module.exports (loader.js:104)
    at Module._reify (loader.js:143)
    at Module.reify (loader.js:130)
```

**Comment by acorncom** [comment]
Confirmed that I'm seeing the same issue as @boris-petrov. Looks like the haxx introduced in https://github.com/ember-polyfills/ember-cached-decorator-polyfill/pull/12 may be causing snags here? Reproduction available here: https://github.com/acorncom/cached-decorator-babel-issues-reproduction (latest ember-cli-babel@7.26.6 in use)

**Comment by acorncom** [comment]
Issue opened at https://github.com/ember-polyfills/ember-cached-decorator-polyfill/issues/77 for this separate issue

**Comment by rwjblue** [comment]
I landed @mydea's PR and released in https://github.com/ember-polyfills/ember-cached-decorator-polyfill/releases/tag/v0.1.2. I also confirmed in @acorncom's reproduction (from #77) works without issue with that update (tested against both Embroider and non-Embroider builds).
